Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -65,27 +65,36 @@ on:
        #      docker scout cves yelb-db:latest > yelb-db-cves.txt
        #      docker scout cves yelb-appserver:latest > yelb-appserver-cves.txt
 jobs:
-     jfrog-integration-check:
-       runs-on: ubuntu-latest
-       steps:
-          
-        - name: Checkout repo
-          uses: actions/checkout@v4
-        
-        - name: Setup JFrog CLI
-          uses: jfrog/setup-jfrog-cli@v3
-      
-        - name: Debug - check jf CLI
-          run: jf --version
+  jfrog-integration-check:
+    runs-on: ubuntu-latest
 
-       
-        - name: Authenticate and check JFrog SaaS connection
-          env:
-             ARTIFACTORY_URL: ${{ secrets.JF_URL }}          # e.g. https://mycompany.jfrog.io/artifactory
-             ARTIFACTORY_USER: ${{ secrets.JFROG_USERNAME }}
-             ARTIFACTORY_API_KEY: ${{ secrets.JFROG_API_KEY }}  # API Key recommended
-             run: |
-               echo "🔐 Checking JFrog SaaS authentication..."
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v4
+
+      - name: Setup JFrog CLI
+        uses: jfrog/setup-jfrog-cli@v3
+
+      - name: Debug - check jf CLI
+        run: jf --version
+
+      - name: Authenticate and check JFrog SaaS connection
+        env:
+          ARTIFACTORY_URL: ${{ secrets.JF_URL }}          # e.g. https://mycompany.jfrog.io/artifactory
+          ARTIFACTORY_USER: ${{ secrets.JFROG_USERNAME }}
+          ARTIFACTORY_API_KEY: ${{ secrets.JFROG_API_KEY }}
+        run: |
+          echo "🔐 Checking JFrog SaaS authentication..."
+
+          response=$(curl -su $ARTIFACTORY_USER:$ARTIFACTORY_API_KEY "$ARTIFACTORY_URL/api/system/ping")
+
+          if [[ "$response" == "OK" ]]; then
+            echo "✅ Successfully connected to JFrog SaaS!"
+          else
+            echo "❌ Failed to connect. Got response: $response"
+            exit 1
+          fi
+
 
 
 
